### ISSUE TITLE
fasterRCNN compilation error with python 3.8 and pytorch 1.12 cuda 11.3

### ISSUE THREAD

**Issue by zee-fee** [yrcong/STTran#36]
I.m trying to setup sttran from scratch and I'm getting errors while setting up fasterRCNN package. 
The command I run is :
`STTran/fasterRCNN/lib: python setup.py install`
```
fatal error: THC/THC.h: No such file or directory
    5 | #include <THC/THC.h>
      |          ^~~~~~~~~~~
compilation terminated.
```

**Comment by yrcong** [comment]
The CUDA version you are using is too high. If you are not using a RTX30 GPU, it is better to downgrade to Cuda10.2.

**Comment by ScottHoang** [comment]
hi zee-fee, you can download the fix here
https://github.com/jwyang/faster-rcnn.pytorch/pull/894

**Comment by zee-fee** [comment]
I downgraded to cuda 10.2 and now it works with torch 1.1
